// ⚠️ GENERADO por scripts/cargar-catalogo.mjs — NO editar a mano.
// Rubro: drugstore · Fuente: scripts/catalogos-seed/drugstore.csv · 200 productos
// Regenerar: node scripts/cargar-catalogo.mjs drugstore
import type { ProductoCatalogo } from "./tipos"

export const categorias: string[] = [
  "Bebidas",
  "Cervezas y vinos",
  "Cigarrillos",
  "Snacks",
  "Golosinas",
  "Almacén",
  "Lácteos",
  "Limpieza",
  "Perfumería",
  "Kiosco"
]

export const proveedores: string[] = [
  "Coca-Cola FEMSA",
  "Pepsico",
  "Distribuidora Norte",
  "La Serenísima",
  "Cervecería Quilmes",
  "Fratelli Branca",
  "Massalin Particulares",
  "British American Tobacco",
  "Mondelez",
  "Arcor",
  "Establecimiento Las Marías",
  "Molinos Río de la Plata",
  "Unilever",
  "Procter & Gamble",
  "Colgate-Palmolive",
  "Mayorista Sur",
  "Kimberly-Clark"
]

export const catalogo: ProductoCatalogo[] = [
  {
    "id": "coca-cola-2-25l",
    "nombre": "Coca-Cola 2.25L",
    "ean": "7790000000010",
    "codigoInterno": "BEB-001",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 3111,
    "precioVenta": 4200,
    "stock": 45,
    "stockMinimo": 12
  },
  {
    "id": "coca-cola-1-5l",
    "nombre": "Coca-Cola 1.5L",
    "ean": "7790000000027",
    "codigoInterno": "BEB-002",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 2370,
    "precioVenta": 3200,
    "stock": 47,
    "stockMinimo": 12
  },
  {
    "id": "coca-cola-lata-354ml",
    "nombre": "Coca-Cola Lata 354ml",
    "ean": "7790000000034",
    "codigoInterno": "BEB-003",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1185,
    "precioVenta": 1600,
    "stock": 6,
    "stockMinimo": 12
  },
  {
    "id": "coca-cola-zero-2-25l",
    "nombre": "Coca-Cola Zero 2.25L",
    "ean": "7790000000041",
    "codigoInterno": "BEB-004",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 3111,
    "precioVenta": 4200,
    "stock": 46,
    "stockMinimo": 12
  },
  {
    "id": "sprite-2-25l",
    "nombre": "Sprite 2.25L",
    "ean": "7790000000058",
    "codigoInterno": "BEB-005",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 2889,
    "precioVenta": 3900,
    "stock": 59,
    "stockMinimo": 12
  },
  {
    "id": "fanta-naranja-2-25l",
    "nombre": "Fanta Naranja 2.25L",
    "ean": "7790000000065",
    "codigoInterno": "BEB-006",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 2889,
    "precioVenta": 3900,
    "stock": 50,
    "stockMinimo": 12
  },
  {
    "id": "pepsi-2-25l",
    "nombre": "Pepsi 2.25L",
    "ean": "7790000000072",
    "codigoInterno": "BEB-007",
    "categoria": "Bebidas",
    "proveedor": "Pepsico",
    "unidadVenta": "unidad",
    "precioCosto": 2667,
    "precioVenta": 3600,
    "stock": 45,
    "stockMinimo": 12
  },
  {
    "id": "seven-up-2-25l",
    "nombre": "Seven Up 2.25L",
    "ean": "7790000000089",
    "codigoInterno": "BEB-008",
    "categoria": "Bebidas",
    "proveedor": "Pepsico",
    "unidadVenta": "unidad",
    "precioCosto": 2667,
    "precioVenta": 3600,
    "stock": 45,
    "stockMinimo": 12
  },
  {
    "id": "manaos-cola-2-25l",
    "nombre": "Manaos Cola 2.25L",
    "ean": "7790000000096",
    "codigoInterno": "BEB-009",
    "categoria": "Bebidas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1556,
    "precioVenta": 2100,
    "stock": 59,
    "stockMinimo": 12
  },
  {
    "id": "manaos-naranja-2-25l",
    "nombre": "Manaos Naranja 2.25L",
    "ean": "7790000000102",
    "codigoInterno": "BEB-010",
    "categoria": "Bebidas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1556,
    "precioVenta": 2100,
    "stock": 36,
    "stockMinimo": 12
  },
  {
    "id": "agua-villa-del-sur-2l",
    "nombre": "Agua Villa del Sur 2L",
    "ean": "7790000000119",
    "codigoInterno": "BEB-011",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1333,
    "precioVenta": 1800,
    "stock": 9,
    "stockMinimo": 12
  },
  {
    "id": "agua-villa-del-sur-con-gas-2l",
    "nombre": "Agua Villa del Sur con gas 2L",
    "ean": "7790000000126",
    "codigoInterno": "BEB-012",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1333,
    "precioVenta": 1800,
    "stock": 49,
    "stockMinimo": 12
  },
  {
    "id": "agua-eco-de-los-andes-2l",
    "nombre": "Agua Eco de los Andes 2L",
    "ean": "7790000000133",
    "codigoInterno": "BEB-013",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1407,
    "precioVenta": 1900,
    "stock": 48,
    "stockMinimo": 12
  },
  {
    "id": "agua-villavicencio-1-5l",
    "nombre": "Agua Villavicencio 1.5L",
    "ean": "7790000000140",
    "codigoInterno": "BEB-014",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1407,
    "precioVenta": 1900,
    "stock": 59,
    "stockMinimo": 12
  },
  {
    "id": "levite-pomelo-2-25l",
    "nombre": "Levité Pomelo 2.25L",
    "ean": "7790000000157",
    "codigoInterno": "BEB-015",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1926,
    "precioVenta": 2600,
    "stock": 47,
    "stockMinimo": 12
  },
  {
    "id": "levite-naranja-1-5l",
    "nombre": "Levité Naranja 1.5L",
    "ean": "7790000000164",
    "codigoInterno": "BEB-016",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1630,
    "precioVenta": 2200,
    "stock": 59,
    "stockMinimo": 12
  },
  {
    "id": "ser-manzana-1-5l",
    "nombre": "Ser Manzana 1.5L",
    "ean": "7790000000171",
    "codigoInterno": "BEB-017",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1630,
    "precioVenta": 2200,
    "stock": 49,
    "stockMinimo": 12
  },
  {
    "id": "aquarius-pera-1-5l",
    "nombre": "Aquarius Pera 1.5L",
    "ean": "7790000000188",
    "codigoInterno": "BEB-018",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1704,
    "precioVenta": 2300,
    "stock": 55,
    "stockMinimo": 12
  },
  {
    "id": "cepita-naranja-1l",
    "nombre": "Cepita Naranja 1L",
    "ean": "7790000000195",
    "codigoInterno": "BEB-019",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1778,
    "precioVenta": 2400,
    "stock": 37,
    "stockMinimo": 12
  },
  {
    "id": "baggio-multifruta-1l",
    "nombre": "Baggio Multifruta 1L",
    "ean": "7790000000201",
    "codigoInterno": "BEB-020",
    "categoria": "Bebidas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1259,
    "precioVenta": 1700,
    "stock": 46,
    "stockMinimo": 12
  },
  {
    "id": "cindor-chocolatada-1l",
    "nombre": "Cindor Chocolatada 1L",
    "ean": "7790000000218",
    "codigoInterno": "BEB-021",
    "categoria": "Bebidas",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 1926,
    "precioVenta": 2600,
    "stock": 58,
    "stockMinimo": 12
  },
  {
    "id": "gatorade-frutas-tropicales-500ml",
    "nombre": "Gatorade Frutas Tropicales 500ml",
    "ean": "7790000000225",
    "codigoInterno": "BEB-022",
    "categoria": "Bebidas",
    "proveedor": "Pepsico",
    "unidadVenta": "unidad",
    "precioCosto": 1556,
    "precioVenta": 2100,
    "stock": 49,
    "stockMinimo": 12
  },
  {
    "id": "powerade-mora-azul-500ml",
    "nombre": "Powerade Mora Azul 500ml",
    "ean": "7790000000232",
    "codigoInterno": "BEB-023",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1556,
    "precioVenta": 2100,
    "stock": 38,
    "stockMinimo": 12
  },
  {
    "id": "red-bull-250ml",
    "nombre": "Red Bull 250ml",
    "ean": "7790000000249",
    "codigoInterno": "BEB-024",
    "categoria": "Bebidas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2370,
    "precioVenta": 3200,
    "stock": 40,
    "stockMinimo": 12
  },
  {
    "id": "speed-energy-500ml",
    "nombre": "Speed Energy 500ml",
    "ean": "7790000000256",
    "codigoInterno": "BEB-025",
    "categoria": "Bebidas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1407,
    "precioVenta": 1900,
    "stock": 59,
    "stockMinimo": 12
  },
  {
    "id": "monster-energy-473ml",
    "nombre": "Monster Energy 473ml",
    "ean": "7790000000263",
    "codigoInterno": "BEB-026",
    "categoria": "Bebidas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2222,
    "precioVenta": 3000,
    "stock": 47,
    "stockMinimo": 12
  },
  {
    "id": "agua-tonica-schweppes-1-5l",
    "nombre": "Agua Tónica Schweppes 1.5L",
    "ean": "7790000000270",
    "codigoInterno": "BEB-027",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1630,
    "precioVenta": 2200,
    "stock": 48,
    "stockMinimo": 12
  },
  {
    "id": "soda-sifon-1-5l",
    "nombre": "Soda Sifón 1.5L",
    "ean": "7790000000287",
    "codigoInterno": "BEB-028",
    "categoria": "Bebidas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1111,
    "precioVenta": 1500,
    "stock": 36,
    "stockMinimo": 12
  },
  {
    "id": "cerveza-quilmes-1l",
    "nombre": "Cerveza Quilmes 1L",
    "ean": "7790000000294",
    "codigoInterno": "CER-001",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 2231,
    "precioVenta": 2900,
    "stock": 4,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-quilmes-lata-473ml",
    "nombre": "Cerveza Quilmes Lata 473ml",
    "ean": "7790000000300",
    "codigoInterno": "CER-002",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 1308,
    "precioVenta": 1700,
    "stock": 26,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-quilmes-porron-340ml",
    "nombre": "Cerveza Quilmes Porrón 340ml",
    "ean": "7790000000317",
    "codigoInterno": "CER-003",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 1154,
    "precioVenta": 1500,
    "stock": 28,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-brahma-1l",
    "nombre": "Cerveza Brahma 1L",
    "ean": "7790000000324",
    "codigoInterno": "CER-004",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 2077,
    "precioVenta": 2700,
    "stock": 42,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-andes-origen-1l",
    "nombre": "Cerveza Andes Origen 1L",
    "ean": "7790000000331",
    "codigoInterno": "CER-005",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 2385,
    "precioVenta": 3100,
    "stock": 46,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-stella-artois-975ml",
    "nombre": "Cerveza Stella Artois 975ml",
    "ean": "7790000000348",
    "codigoInterno": "CER-006",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 2769,
    "precioVenta": 3600,
    "stock": 32,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-corona-330ml",
    "nombre": "Cerveza Corona 330ml",
    "ean": "7790000000355",
    "codigoInterno": "CER-007",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 2000,
    "precioVenta": 2600,
    "stock": 37,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-heineken-lata-473ml",
    "nombre": "Cerveza Heineken Lata 473ml",
    "ean": "7790000000362",
    "codigoInterno": "CER-008",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 1846,
    "precioVenta": 2400,
    "stock": 41,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-schneider-1l",
    "nombre": "Cerveza Schneider 1L",
    "ean": "7790000000379",
    "codigoInterno": "CER-009",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 1923,
    "precioVenta": 2500,
    "stock": 47,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-imperial-1l",
    "nombre": "Cerveza Imperial 1L",
    "ean": "7790000000386",
    "codigoInterno": "CER-010",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 2308,
    "precioVenta": 3000,
    "stock": 30,
    "stockMinimo": 8
  },
  {
    "id": "cerveza-patagonia-amber-lager-730ml",
    "nombre": "Cerveza Patagonia Amber Lager 730ml",
    "ean": "7790000000393",
    "codigoInterno": "CER-011",
    "categoria": "Cervezas y vinos",
    "proveedor": "Cervecería Quilmes",
    "unidadVenta": "unidad",
    "precioCosto": 2923,
    "precioVenta": 3800,
    "stock": 35,
    "stockMinimo": 8
  },
  {
    "id": "fernet-branca-750ml",
    "nombre": "Fernet Branca 750ml",
    "ean": "7790000000409",
    "codigoInterno": "CER-012",
    "categoria": "Cervezas y vinos",
    "proveedor": "Fratelli Branca",
    "unidadVenta": "unidad",
    "precioCosto": 11154,
    "precioVenta": 14500,
    "stock": 5,
    "stockMinimo": 8
  },
  {
    "id": "fernet-branca-450ml",
    "nombre": "Fernet Branca 450ml",
    "ean": "7790000000416",
    "codigoInterno": "CER-013",
    "categoria": "Cervezas y vinos",
    "proveedor": "Fratelli Branca",
    "unidadVenta": "unidad",
    "precioCosto": 7308,
    "precioVenta": 9500,
    "stock": 29,
    "stockMinimo": 8
  },
  {
    "id": "fernet-1882-750ml",
    "nombre": "Fernet 1882 750ml",
    "ean": "7790000000423",
    "codigoInterno": "CER-014",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 7538,
    "precioVenta": 9800,
    "stock": 31,
    "stockMinimo": 8
  },
  {
    "id": "vino-toro-tinto-1l",
    "nombre": "Vino Toro Tinto 1L",
    "ean": "7790000000430",
    "codigoInterno": "CER-015",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2000,
    "precioVenta": 2600,
    "stock": 44,
    "stockMinimo": 8
  },
  {
    "id": "vino-termidor-tinto-1l",
    "nombre": "Vino Termidor Tinto 1L",
    "ean": "7790000000447",
    "codigoInterno": "CER-016",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2077,
    "precioVenta": 2700,
    "stock": 44,
    "stockMinimo": 8
  },
  {
    "id": "vino-uvita-tinto-1l",
    "nombre": "Vino Uvita Tinto 1L",
    "ean": "7790000000454",
    "codigoInterno": "CER-017",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1846,
    "precioVenta": 2400,
    "stock": 34,
    "stockMinimo": 8
  },
  {
    "id": "vino-dada-malbec-750ml",
    "nombre": "Vino Dada Malbec 750ml",
    "ean": "7790000000461",
    "codigoInterno": "CER-018",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2923,
    "precioVenta": 3800,
    "stock": 41,
    "stockMinimo": 8
  },
  {
    "id": "vino-benjamin-nieto-malbec-750ml",
    "nombre": "Vino Benjamín Nieto Malbec 750ml",
    "ean": "7790000000478",
    "codigoInterno": "CER-019",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 4000,
    "precioVenta": 5200,
    "stock": 36,
    "stockMinimo": 8
  },
  {
    "id": "vino-los-toneles-malbec-750ml",
    "nombre": "Vino Los Toneles Malbec 750ml",
    "ean": "7790000000485",
    "codigoInterno": "CER-020",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 3231,
    "precioVenta": 4200,
    "stock": 27,
    "stockMinimo": 8
  },
  {
    "id": "gancia-americano-950ml",
    "nombre": "Gancia Americano 950ml",
    "ean": "7790000000492",
    "codigoInterno": "CER-021",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 5231,
    "precioVenta": 6800,
    "stock": 28,
    "stockMinimo": 8
  },
  {
    "id": "campari-750ml",
    "nombre": "Campari 750ml",
    "ean": "7790000000508",
    "codigoInterno": "CER-022",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 7077,
    "precioVenta": 9200,
    "stock": 44,
    "stockMinimo": 8
  },
  {
    "id": "vodka-smirnoff-750ml",
    "nombre": "Vodka Smirnoff 750ml",
    "ean": "7790000000515",
    "codigoInterno": "CER-023",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 7538,
    "precioVenta": 9800,
    "stock": 26,
    "stockMinimo": 8
  },
  {
    "id": "sidra-real-720ml",
    "nombre": "Sidra Real 720ml",
    "ean": "7790000000522",
    "codigoInterno": "CER-024",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2462,
    "precioVenta": 3200,
    "stock": 47,
    "stockMinimo": 8
  },
  {
    "id": "sidra-1888-720ml",
    "nombre": "Sidra 1888 720ml",
    "ean": "7790000000539",
    "codigoInterno": "CER-025",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2769,
    "precioVenta": 3600,
    "stock": 28,
    "stockMinimo": 8
  },
  {
    "id": "aperitivo-cynar-750ml",
    "nombre": "Aperitivo Cynar 750ml",
    "ean": "7790000000546",
    "codigoInterno": "CER-026",
    "categoria": "Cervezas y vinos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 6308,
    "precioVenta": 8200,
    "stock": 25,
    "stockMinimo": 8
  },
  {
    "id": "marlboro-box-20",
    "nombre": "Marlboro Box 20",
    "ean": "7790000000553",
    "codigoInterno": "CIG-001",
    "categoria": "Cigarrillos",
    "proveedor": "Massalin Particulares",
    "unidadVenta": "unidad",
    "precioCosto": 3393,
    "precioVenta": 3800,
    "stock": 6,
    "stockMinimo": 10
  },
  {
    "id": "marlboro-red-box-10",
    "nombre": "Marlboro Red Box 10",
    "ean": "7790000000560",
    "codigoInterno": "CIG-002",
    "categoria": "Cigarrillos",
    "proveedor": "Massalin Particulares",
    "unidadVenta": "unidad",
    "precioCosto": 1875,
    "precioVenta": 2100,
    "stock": 39,
    "stockMinimo": 10
  },
  {
    "id": "marlboro-gold-box-20",
    "nombre": "Marlboro Gold Box 20",
    "ean": "7790000000577",
    "codigoInterno": "CIG-003",
    "categoria": "Cigarrillos",
    "proveedor": "Massalin Particulares",
    "unidadVenta": "unidad",
    "precioCosto": 3393,
    "precioVenta": 3800,
    "stock": 50,
    "stockMinimo": 10
  },
  {
    "id": "philip-morris-box-20",
    "nombre": "Philip Morris Box 20",
    "ean": "7790000000584",
    "codigoInterno": "CIG-004",
    "categoria": "Cigarrillos",
    "proveedor": "Massalin Particulares",
    "unidadVenta": "unidad",
    "precioCosto": 3125,
    "precioVenta": 3500,
    "stock": 54,
    "stockMinimo": 10
  },
  {
    "id": "philip-morris-ks-20",
    "nombre": "Philip Morris KS 20",
    "ean": "7790000000591",
    "codigoInterno": "CIG-005",
    "categoria": "Cigarrillos",
    "proveedor": "Massalin Particulares",
    "unidadVenta": "unidad",
    "precioCosto": 3036,
    "precioVenta": 3400,
    "stock": 44,
    "stockMinimo": 10
  },
  {
    "id": "chesterfield-box-20",
    "nombre": "Chesterfield Box 20",
    "ean": "7790000000607",
    "codigoInterno": "CIG-006",
    "categoria": "Cigarrillos",
    "proveedor": "Massalin Particulares",
    "unidadVenta": "unidad",
    "precioCosto": 2946,
    "precioVenta": 3300,
    "stock": 30,
    "stockMinimo": 10
  },
  {
    "id": "parliament-box-20",
    "nombre": "Parliament Box 20",
    "ean": "7790000000614",
    "codigoInterno": "CIG-007",
    "categoria": "Cigarrillos",
    "proveedor": "Massalin Particulares",
    "unidadVenta": "unidad",
    "precioCosto": 3750,
    "precioVenta": 4200,
    "stock": 44,
    "stockMinimo": 10
  },
  {
    "id": "camel-box-20",
    "nombre": "Camel Box 20",
    "ean": "7790000000621",
    "codigoInterno": "CIG-008",
    "categoria": "Cigarrillos",
    "proveedor": "British American Tobacco",
    "unidadVenta": "unidad",
    "precioCosto": 3214,
    "precioVenta": 3600,
    "stock": 49,
    "stockMinimo": 10
  },
  {
    "id": "lucky-strike-box-20",
    "nombre": "Lucky Strike Box 20",
    "ean": "7790000000638",
    "codigoInterno": "CIG-009",
    "categoria": "Cigarrillos",
    "proveedor": "British American Tobacco",
    "unidadVenta": "unidad",
    "precioCosto": 3125,
    "precioVenta": 3500,
    "stock": 30,
    "stockMinimo": 10
  },
  {
    "id": "viceroy-box-20",
    "nombre": "Viceroy Box 20",
    "ean": "7790000000645",
    "codigoInterno": "CIG-010",
    "categoria": "Cigarrillos",
    "proveedor": "British American Tobacco",
    "unidadVenta": "unidad",
    "precioCosto": 2679,
    "precioVenta": 3000,
    "stock": 31,
    "stockMinimo": 10
  },
  {
    "id": "pall-mall-box-20",
    "nombre": "Pall Mall Box 20",
    "ean": "7790000000652",
    "codigoInterno": "CIG-011",
    "categoria": "Cigarrillos",
    "proveedor": "British American Tobacco",
    "unidadVenta": "unidad",
    "precioCosto": 2768,
    "precioVenta": 3100,
    "stock": 54,
    "stockMinimo": 10
  },
  {
    "id": "jockey-club-suave-20",
    "nombre": "Jockey Club Suave 20",
    "ean": "7790000000669",
    "codigoInterno": "CIG-012",
    "categoria": "Cigarrillos",
    "proveedor": "British American Tobacco",
    "unidadVenta": "unidad",
    "precioCosto": 2589,
    "precioVenta": 2900,
    "stock": 53,
    "stockMinimo": 10
  },
  {
    "id": "colorado-20",
    "nombre": "Colorado 20",
    "ean": "7790000000676",
    "codigoInterno": "CIG-013",
    "categoria": "Cigarrillos",
    "proveedor": "Massalin Particulares",
    "unidadVenta": "unidad",
    "precioCosto": 2321,
    "precioVenta": 2600,
    "stock": 32,
    "stockMinimo": 10
  },
  {
    "id": "derby-box-20",
    "nombre": "Derby Box 20",
    "ean": "7790000000683",
    "codigoInterno": "CIG-014",
    "categoria": "Cigarrillos",
    "proveedor": "British American Tobacco",
    "unidadVenta": "unidad",
    "precioCosto": 2232,
    "precioVenta": 2500,
    "stock": 46,
    "stockMinimo": 10
  },
  {
    "id": "next-box-20",
    "nombre": "Next Box 20",
    "ean": "7790000000690",
    "codigoInterno": "CIG-015",
    "categoria": "Cigarrillos",
    "proveedor": "British American Tobacco",
    "unidadVenta": "unidad",
    "precioCosto": 2411,
    "precioVenta": 2700,
    "stock": 30,
    "stockMinimo": 10
  },
  {
    "id": "parisiennes-20",
    "nombre": "Parisiennes 20",
    "ean": "7790000000706",
    "codigoInterno": "CIG-016",
    "categoria": "Cigarrillos",
    "proveedor": "Massalin Particulares",
    "unidadVenta": "unidad",
    "precioCosto": 2500,
    "precioVenta": 2800,
    "stock": 50,
    "stockMinimo": 10
  },
  {
    "id": "papas-lays-clasicas-145g",
    "nombre": "Papas Lays Clásicas 145g",
    "ean": "7790000000713",
    "codigoInterno": "SNA-001",
    "categoria": "Snacks",
    "proveedor": "Pepsico",
    "unidadVenta": "unidad",
    "precioCosto": 2138,
    "precioVenta": 3100,
    "stock": 52,
    "stockMinimo": 10
  },
  {
    "id": "papas-lays-cebolla-145g",
    "nombre": "Papas Lays Cebolla 145g",
    "ean": "7790000000720",
    "codigoInterno": "SNA-002",
    "categoria": "Snacks",
    "proveedor": "Pepsico",
    "unidadVenta": "unidad",
    "precioCosto": 2138,
    "precioVenta": 3100,
    "stock": 33,
    "stockMinimo": 10
  },
  {
    "id": "pringles-original-124g",
    "nombre": "Pringles Original 124g",
    "ean": "7790000000737",
    "codigoInterno": "SNA-003",
    "categoria": "Snacks",
    "proveedor": "Pepsico",
    "unidadVenta": "unidad",
    "precioCosto": 2897,
    "precioVenta": 4200,
    "stock": 35,
    "stockMinimo": 10
  },
  {
    "id": "papas-pehuamar-clasicas-130g",
    "nombre": "Papas Pehuamar Clásicas 130g",
    "ean": "7790000000744",
    "codigoInterno": "SNA-004",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1793,
    "precioVenta": 2600,
    "stock": 50,
    "stockMinimo": 10
  },
  {
    "id": "doritos-queso-140g",
    "nombre": "Doritos Queso 140g",
    "ean": "7790000000751",
    "codigoInterno": "SNA-005",
    "categoria": "Snacks",
    "proveedor": "Pepsico",
    "unidadVenta": "unidad",
    "precioCosto": 2276,
    "precioVenta": 3300,
    "stock": 37,
    "stockMinimo": 10
  },
  {
    "id": "cheetos-pelotitas-90g",
    "nombre": "Cheetos Pelotitas 90g",
    "ean": "7790000000768",
    "codigoInterno": "SNA-006",
    "categoria": "Snacks",
    "proveedor": "Pepsico",
    "unidadVenta": "unidad",
    "precioCosto": 1448,
    "precioVenta": 2100,
    "stock": 34,
    "stockMinimo": 10
  },
  {
    "id": "palitos-salados-pehuamar-100g",
    "nombre": "Palitos Salados Pehuamar 100g",
    "ean": "7790000000775",
    "codigoInterno": "SNA-007",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1103,
    "precioVenta": 1600,
    "stock": 37,
    "stockMinimo": 10
  },
  {
    "id": "chizitos-pehuamar-90g",
    "nombre": "Chizitos Pehuamar 90g",
    "ean": "7790000000782",
    "codigoInterno": "SNA-008",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1241,
    "precioVenta": 1800,
    "stock": 39,
    "stockMinimo": 10
  },
  {
    "id": "twistos-mix-100g",
    "nombre": "Twistos Mix 100g",
    "ean": "7790000000799",
    "codigoInterno": "SNA-009",
    "categoria": "Snacks",
    "proveedor": "Pepsico",
    "unidadVenta": "unidad",
    "precioCosto": 1517,
    "precioVenta": 2200,
    "stock": 47,
    "stockMinimo": 10
  },
  {
    "id": "mani-salado-krachitos-90g",
    "nombre": "Maní Salado Krachitos 90g",
    "ean": "7790000000805",
    "codigoInterno": "SNA-010",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1172,
    "precioVenta": 1700,
    "stock": 35,
    "stockMinimo": 10
  },
  {
    "id": "mani-japones-krachitos-100g",
    "nombre": "Maní Japonés Krachitos 100g",
    "ean": "7790000000812",
    "codigoInterno": "SNA-011",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1310,
    "precioVenta": 1900,
    "stock": 48,
    "stockMinimo": 10
  },
  {
    "id": "nachos-con-queso-150g",
    "nombre": "Nachos con Queso 150g",
    "ean": "7790000000829",
    "codigoInterno": "SNA-012",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2069,
    "precioVenta": 3000,
    "stock": 44,
    "stockMinimo": 10
  },
  {
    "id": "snacks-mix-frutos-secos-100g",
    "nombre": "Snacks Mix Frutos Secos 100g",
    "ean": "7790000000836",
    "codigoInterno": "SNA-013",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2414,
    "precioVenta": 3500,
    "stock": 42,
    "stockMinimo": 10
  },
  {
    "id": "galletitas-club-social-100g",
    "nombre": "Galletitas Club Social 100g",
    "ean": "7790000000843",
    "codigoInterno": "SNA-014",
    "categoria": "Snacks",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 1034,
    "precioVenta": 1500,
    "stock": 47,
    "stockMinimo": 10
  },
  {
    "id": "aceitunas-verdes-200g",
    "nombre": "Aceitunas Verdes 200g",
    "ean": "7790000000850",
    "codigoInterno": "SNA-015",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1793,
    "precioVenta": 2600,
    "stock": 51,
    "stockMinimo": 10
  },
  {
    "id": "palitos-de-la-selva-100g",
    "nombre": "Palitos de la Selva 100g",
    "ean": "7790000000867",
    "codigoInterno": "SNA-016",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1103,
    "precioVenta": 1600,
    "stock": 33,
    "stockMinimo": 10
  },
  {
    "id": "papas-fritas-onduladas-200g",
    "nombre": "Papas Fritas Onduladas 200g",
    "ean": "7790000000874",
    "codigoInterno": "SNA-017",
    "categoria": "Snacks",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2483,
    "precioVenta": 3600,
    "stock": 38,
    "stockMinimo": 10
  },
  {
    "id": "mani-con-chocolate-100g",
    "nombre": "Maní con Chocolate 100g",
    "ean": "7790000000881",
    "codigoInterno": "SNA-018",
    "categoria": "Snacks",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 1517,
    "precioVenta": 2200,
    "stock": 37,
    "stockMinimo": 10
  },
  {
    "id": "alfajor-jorgito-chocolate",
    "nombre": "Alfajor Jorgito Chocolate",
    "ean": "7790000000898",
    "codigoInterno": "GOL-001",
    "categoria": "Golosinas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 621,
    "precioVenta": 900,
    "stock": 8,
    "stockMinimo": 15
  },
  {
    "id": "alfajor-guaymallen-simple",
    "nombre": "Alfajor Guaymallén Simple",
    "ean": "7790000000904",
    "codigoInterno": "GOL-002",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 448,
    "precioVenta": 650,
    "stock": 67,
    "stockMinimo": 15
  },
  {
    "id": "alfajor-milka-oreo",
    "nombre": "Alfajor Milka Oreo",
    "ean": "7790000000911",
    "codigoInterno": "GOL-003",
    "categoria": "Golosinas",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 1103,
    "precioVenta": 1600,
    "stock": 60,
    "stockMinimo": 15
  },
  {
    "id": "alfajor-aguila-negro",
    "nombre": "Alfajor Águila Negro",
    "ean": "7790000000928",
    "codigoInterno": "GOL-004",
    "categoria": "Golosinas",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 966,
    "precioVenta": 1400,
    "stock": 55,
    "stockMinimo": 15
  },
  {
    "id": "alfajor-terrabusi-doble",
    "nombre": "Alfajor Terrabusi Doble",
    "ean": "7790000000935",
    "codigoInterno": "GOL-005",
    "categoria": "Golosinas",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 1034,
    "precioVenta": 1500,
    "stock": 62,
    "stockMinimo": 15
  },
  {
    "id": "alfajor-fantoche-triple",
    "nombre": "Alfajor Fantoche Triple",
    "ean": "7790000000942",
    "codigoInterno": "GOL-006",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 897,
    "precioVenta": 1300,
    "stock": 47,
    "stockMinimo": 15
  },
  {
    "id": "alfajor-tofi-clasico",
    "nombre": "Alfajor Tofi Clásico",
    "ean": "7790000000959",
    "codigoInterno": "GOL-007",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 828,
    "precioVenta": 1200,
    "stock": 56,
    "stockMinimo": 15
  },
  {
    "id": "chocolate-milka-leche-100g",
    "nombre": "Chocolate Milka Leche 100g",
    "ean": "7790000000966",
    "codigoInterno": "GOL-008",
    "categoria": "Golosinas",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 2207,
    "precioVenta": 3200,
    "stock": 51,
    "stockMinimo": 15
  },
  {
    "id": "chocolate-cofler-aireado-100g",
    "nombre": "Chocolate Cofler Aireado 100g",
    "ean": "7790000000973",
    "codigoInterno": "GOL-009",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 2000,
    "precioVenta": 2900,
    "stock": 64,
    "stockMinimo": 15
  },
  {
    "id": "chocolate-block-100g",
    "nombre": "Chocolate Block 100g",
    "ean": "7790000000980",
    "codigoInterno": "GOL-010",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 1931,
    "precioVenta": 2800,
    "stock": 69,
    "stockMinimo": 15
  },
  {
    "id": "kinder-bueno-43g",
    "nombre": "Kinder Bueno 43g",
    "ean": "7790000000997",
    "codigoInterno": "GOL-011",
    "categoria": "Golosinas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1517,
    "precioVenta": 2200,
    "stock": 62,
    "stockMinimo": 15
  },
  {
    "id": "chocolate-shot-100g",
    "nombre": "Chocolate Shot 100g",
    "ean": "7790000001000",
    "codigoInterno": "GOL-012",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 1793,
    "precioVenta": 2600,
    "stock": 45,
    "stockMinimo": 15
  },
  {
    "id": "rhodesia-27g",
    "nombre": "Rhodesia 27g",
    "ean": "7790000001017",
    "codigoInterno": "GOL-013",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 621,
    "precioVenta": 900,
    "stock": 54,
    "stockMinimo": 15
  },
  {
    "id": "bon-o-bon-unidad",
    "nombre": "Bon o Bon Unidad",
    "ean": "7790000001024",
    "codigoInterno": "GOL-014",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 414,
    "precioVenta": 600,
    "stock": 62,
    "stockMinimo": 15
  },
  {
    "id": "oblea-opera",
    "nombre": "Oblea Ópera",
    "ean": "7790000001031",
    "codigoInterno": "GOL-015",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 483,
    "precioVenta": 700,
    "stock": 55,
    "stockMinimo": 15
  },
  {
    "id": "chupetin-pico-dulce",
    "nombre": "Chupetín Pico Dulce",
    "ean": "7790000001048",
    "codigoInterno": "GOL-016",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 276,
    "precioVenta": 400,
    "stock": 63,
    "stockMinimo": 15
  },
  {
    "id": "chicle-beldent-menta",
    "nombre": "Chicle Beldent Menta",
    "ean": "7790000001055",
    "codigoInterno": "GOL-017",
    "categoria": "Golosinas",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 621,
    "precioVenta": 900,
    "stock": 50,
    "stockMinimo": 15
  },
  {
    "id": "chicle-topline-menta",
    "nombre": "Chicle Topline Menta",
    "ean": "7790000001062",
    "codigoInterno": "GOL-018",
    "categoria": "Golosinas",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 655,
    "precioVenta": 950,
    "stock": 59,
    "stockMinimo": 15
  },
  {
    "id": "caramelos-sugus-surtidos-30u",
    "nombre": "Caramelos Sugus Surtidos 30u",
    "ean": "7790000001079",
    "codigoInterno": "GOL-019",
    "categoria": "Golosinas",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 1448,
    "precioVenta": 2100,
    "stock": 55,
    "stockMinimo": 15
  },
  {
    "id": "caramelos-flynn-paff-400g",
    "nombre": "Caramelos Flynn Paff 400g",
    "ean": "7790000001086",
    "codigoInterno": "GOL-020",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 2621,
    "precioVenta": 3800,
    "stock": 50,
    "stockMinimo": 15
  },
  {
    "id": "caramelos-media-hora-300g",
    "nombre": "Caramelos Media Hora 300g",
    "ean": "7790000001093",
    "codigoInterno": "GOL-021",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 1793,
    "precioVenta": 2600,
    "stock": 48,
    "stockMinimo": 15
  },
  {
    "id": "pastillas-menthoplus-miel",
    "nombre": "Pastillas Menthoplus Miel",
    "ean": "7790000001109",
    "codigoInterno": "GOL-022",
    "categoria": "Golosinas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 586,
    "precioVenta": 850,
    "stock": 49,
    "stockMinimo": 15
  },
  {
    "id": "pastillas-tic-tac-menta",
    "nombre": "Pastillas Tic Tac Menta",
    "ean": "7790000001116",
    "codigoInterno": "GOL-023",
    "categoria": "Golosinas",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 966,
    "precioVenta": 1400,
    "stock": 54,
    "stockMinimo": 15
  },
  {
    "id": "turron-arcor-25g",
    "nombre": "Turrón Arcor 25g",
    "ean": "7790000001123",
    "codigoInterno": "GOL-024",
    "categoria": "Golosinas",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 379,
    "precioVenta": 550,
    "stock": 57,
    "stockMinimo": 15
  },
  {
    "id": "yerba-taragui-1kg",
    "nombre": "Yerba Taragüí 1kg",
    "ean": "7790000001130",
    "codigoInterno": "ALM-001",
    "categoria": "Almacén",
    "proveedor": "Establecimiento Las Marías",
    "unidadVenta": "unidad",
    "precioCosto": 3828,
    "precioVenta": 4900,
    "stock": 55,
    "stockMinimo": 12
  },
  {
    "id": "yerba-rosamonte-1kg",
    "nombre": "Yerba Rosamonte 1kg",
    "ean": "7790000001147",
    "codigoInterno": "ALM-002",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 3672,
    "precioVenta": 4700,
    "stock": 45,
    "stockMinimo": 12
  },
  {
    "id": "yerba-playadito-1kg",
    "nombre": "Yerba Playadito 1kg",
    "ean": "7790000001154",
    "codigoInterno": "ALM-003",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 3594,
    "precioVenta": 4600,
    "stock": 5,
    "stockMinimo": 12
  },
  {
    "id": "yerba-cbse-hierbas-500g",
    "nombre": "Yerba CBSé Hierbas 500g",
    "ean": "7790000001161",
    "codigoInterno": "ALM-004",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2188,
    "precioVenta": 2800,
    "stock": 45,
    "stockMinimo": 12
  },
  {
    "id": "yerba-la-merced-despalada-1kg",
    "nombre": "Yerba La Merced Despalada 1kg",
    "ean": "7790000001178",
    "codigoInterno": "ALM-005",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 3984,
    "precioVenta": 5100,
    "stock": 53,
    "stockMinimo": 12
  },
  {
    "id": "azucar-ledesma-1kg",
    "nombre": "Azúcar Ledesma 1kg",
    "ean": "7790000001185",
    "codigoInterno": "ALM-006",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1484,
    "precioVenta": 1900,
    "stock": 47,
    "stockMinimo": 12
  },
  {
    "id": "sal-fina-celusal-500g",
    "nombre": "Sal Fina Celusal 500g",
    "ean": "7790000001192",
    "codigoInterno": "ALM-007",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 703,
    "precioVenta": 900,
    "stock": 50,
    "stockMinimo": 12
  },
  {
    "id": "harina-0000-blancaflor-1kg",
    "nombre": "Harina 0000 Blancaflor 1kg",
    "ean": "7790000001208",
    "codigoInterno": "ALM-008",
    "categoria": "Almacén",
    "proveedor": "Molinos Río de la Plata",
    "unidadVenta": "unidad",
    "precioCosto": 1250,
    "precioVenta": 1600,
    "stock": 52,
    "stockMinimo": 12
  },
  {
    "id": "harina-leudante-pureza-1kg",
    "nombre": "Harina Leudante Pureza 1kg",
    "ean": "7790000001215",
    "codigoInterno": "ALM-009",
    "categoria": "Almacén",
    "proveedor": "Molinos Río de la Plata",
    "unidadVenta": "unidad",
    "precioCosto": 1328,
    "precioVenta": 1700,
    "stock": 47,
    "stockMinimo": 12
  },
  {
    "id": "fideos-matarazzo-tirabuzon-500g",
    "nombre": "Fideos Matarazzo Tirabuzón 500g",
    "ean": "7790000001222",
    "codigoInterno": "ALM-010",
    "categoria": "Almacén",
    "proveedor": "Molinos Río de la Plata",
    "unidadVenta": "unidad",
    "precioCosto": 1172,
    "precioVenta": 1500,
    "stock": 51,
    "stockMinimo": 12
  },
  {
    "id": "fideos-lucchetti-spaghetti-500g",
    "nombre": "Fideos Lucchetti Spaghetti 500g",
    "ean": "7790000001239",
    "codigoInterno": "ALM-011",
    "categoria": "Almacén",
    "proveedor": "Molinos Río de la Plata",
    "unidadVenta": "unidad",
    "precioCosto": 1172,
    "precioVenta": 1500,
    "stock": 44,
    "stockMinimo": 12
  },
  {
    "id": "arroz-gallo-oro-1kg",
    "nombre": "Arroz Gallo Oro 1kg",
    "ean": "7790000001246",
    "codigoInterno": "ALM-012",
    "categoria": "Almacén",
    "proveedor": "Molinos Río de la Plata",
    "unidadVenta": "unidad",
    "precioCosto": 2031,
    "precioVenta": 2600,
    "stock": 40,
    "stockMinimo": 12
  },
  {
    "id": "aceite-cocinero-girasol-1-5l",
    "nombre": "Aceite Cocinero Girasol 1.5L",
    "ean": "7790000001253",
    "codigoInterno": "ALM-013",
    "categoria": "Almacén",
    "proveedor": "Molinos Río de la Plata",
    "unidadVenta": "unidad",
    "precioCosto": 3281,
    "precioVenta": 4200,
    "stock": 53,
    "stockMinimo": 12
  },
  {
    "id": "aceite-natura-girasol-900ml",
    "nombre": "Aceite Natura Girasol 900ml",
    "ean": "7790000001260",
    "codigoInterno": "ALM-014",
    "categoria": "Almacén",
    "proveedor": "Molinos Río de la Plata",
    "unidadVenta": "unidad",
    "precioCosto": 2266,
    "precioVenta": 2900,
    "stock": 60,
    "stockMinimo": 12
  },
  {
    "id": "pure-de-tomate-arcor-520g",
    "nombre": "Puré de Tomate Arcor 520g",
    "ean": "7790000001277",
    "codigoInterno": "ALM-015",
    "categoria": "Almacén",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 1094,
    "precioVenta": 1400,
    "stock": 58,
    "stockMinimo": 12
  },
  {
    "id": "arvejas-la-campagnola-300g",
    "nombre": "Arvejas La Campagnola 300g",
    "ean": "7790000001284",
    "codigoInterno": "ALM-016",
    "categoria": "Almacén",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 1172,
    "precioVenta": 1500,
    "stock": 60,
    "stockMinimo": 12
  },
  {
    "id": "atun-la-campagnola-170g",
    "nombre": "Atún La Campagnola 170g",
    "ean": "7790000001291",
    "codigoInterno": "ALM-017",
    "categoria": "Almacén",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 2500,
    "precioVenta": 3200,
    "stock": 50,
    "stockMinimo": 12
  },
  {
    "id": "mayonesa-hellmann-s-500g",
    "nombre": "Mayonesa Hellmann's 500g",
    "ean": "7790000001307",
    "codigoInterno": "ALM-018",
    "categoria": "Almacén",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 2422,
    "precioVenta": 3100,
    "stock": 47,
    "stockMinimo": 12
  },
  {
    "id": "ketchup-hellmann-s-500g",
    "nombre": "Ketchup Hellmann's 500g",
    "ean": "7790000001314",
    "codigoInterno": "ALM-019",
    "categoria": "Almacén",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 2266,
    "precioVenta": 2900,
    "stock": 50,
    "stockMinimo": 12
  },
  {
    "id": "cafe-la-virginia-250g",
    "nombre": "Café La Virginia 250g",
    "ean": "7790000001321",
    "codigoInterno": "ALM-020",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 3750,
    "precioVenta": 4800,
    "stock": 56,
    "stockMinimo": 12
  },
  {
    "id": "nescafe-clasico-170g",
    "nombre": "Nescafé Clásico 170g",
    "ean": "7790000001338",
    "codigoInterno": "ALM-021",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 5625,
    "precioVenta": 7200,
    "stock": 46,
    "stockMinimo": 12
  },
  {
    "id": "te-taragui-25-saquitos",
    "nombre": "Té Taragüí 25 saquitos",
    "ean": "7790000001345",
    "codigoInterno": "ALM-022",
    "categoria": "Almacén",
    "proveedor": "Establecimiento Las Marías",
    "unidadVenta": "unidad",
    "precioCosto": 1484,
    "precioVenta": 1900,
    "stock": 56,
    "stockMinimo": 12
  },
  {
    "id": "mate-cocido-la-virginia-25-saquitos",
    "nombre": "Mate Cocido La Virginia 25 saquitos",
    "ean": "7790000001352",
    "codigoInterno": "ALM-023",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1563,
    "precioVenta": 2000,
    "stock": 54,
    "stockMinimo": 12
  },
  {
    "id": "galletitas-criollitas-100g",
    "nombre": "Galletitas Criollitas 100g",
    "ean": "7790000001369",
    "codigoInterno": "ALM-024",
    "categoria": "Almacén",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 1016,
    "precioVenta": 1300,
    "stock": 57,
    "stockMinimo": 12
  },
  {
    "id": "galletitas-traviata-100g",
    "nombre": "Galletitas Traviata 100g",
    "ean": "7790000001376",
    "codigoInterno": "ALM-025",
    "categoria": "Almacén",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 1016,
    "precioVenta": 1300,
    "stock": 49,
    "stockMinimo": 12
  },
  {
    "id": "galletitas-chocolinas-170g",
    "nombre": "Galletitas Chocolinas 170g",
    "ean": "7790000001383",
    "codigoInterno": "ALM-026",
    "categoria": "Almacén",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 1875,
    "precioVenta": 2400,
    "stock": 55,
    "stockMinimo": 12
  },
  {
    "id": "galletitas-rex-100g",
    "nombre": "Galletitas Rex 100g",
    "ean": "7790000001390",
    "codigoInterno": "ALM-027",
    "categoria": "Almacén",
    "proveedor": "Mondelez",
    "unidadVenta": "unidad",
    "precioCosto": 938,
    "precioVenta": 1200,
    "stock": 45,
    "stockMinimo": 12
  },
  {
    "id": "dulce-de-leche-la-serenisima-400g",
    "nombre": "Dulce de Leche La Serenísima 400g",
    "ean": "7790000001406",
    "codigoInterno": "ALM-028",
    "categoria": "Almacén",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 2500,
    "precioVenta": 3200,
    "stock": 40,
    "stockMinimo": 12
  },
  {
    "id": "mermelada-arcor-durazno-390g",
    "nombre": "Mermelada Arcor Durazno 390g",
    "ean": "7790000001413",
    "codigoInterno": "ALM-029",
    "categoria": "Almacén",
    "proveedor": "Arcor",
    "unidadVenta": "unidad",
    "precioCosto": 1875,
    "precioVenta": 2400,
    "stock": 60,
    "stockMinimo": 12
  },
  {
    "id": "cacao-nesquik-400g",
    "nombre": "Cacao Nesquik 400g",
    "ean": "7790000001420",
    "codigoInterno": "ALM-030",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 3594,
    "precioVenta": 4600,
    "stock": 48,
    "stockMinimo": 12
  },
  {
    "id": "leche-la-serenisima-sachet-1l",
    "nombre": "Leche La Serenísima Sachet 1L",
    "ean": "7790000001437",
    "codigoInterno": "LAC-001",
    "categoria": "Lácteos",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 1200,
    "precioVenta": 1500,
    "stock": 6,
    "stockMinimo": 8
  },
  {
    "id": "leche-la-serenisima-larga-vida-1l",
    "nombre": "Leche La Serenísima Larga Vida 1L",
    "ean": "7790000001444",
    "codigoInterno": "LAC-002",
    "categoria": "Lácteos",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 1440,
    "precioVenta": 1800,
    "stock": 33,
    "stockMinimo": 8
  },
  {
    "id": "leche-sancor-sachet-1l",
    "nombre": "Leche Sancor Sachet 1L",
    "ean": "7790000001451",
    "codigoInterno": "LAC-003",
    "categoria": "Lácteos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1160,
    "precioVenta": 1450,
    "stock": 43,
    "stockMinimo": 8
  },
  {
    "id": "yogur-ser-bebible-frutilla-900g",
    "nombre": "Yogur Ser Bebible Frutilla 900g",
    "ean": "7790000001468",
    "codigoInterno": "LAC-004",
    "categoria": "Lácteos",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 2320,
    "precioVenta": 2900,
    "stock": 33,
    "stockMinimo": 8
  },
  {
    "id": "yogur-yogurisimo-firme-190g",
    "nombre": "Yogur Yogurísimo Firme 190g",
    "ean": "7790000001475",
    "codigoInterno": "LAC-005",
    "categoria": "Lácteos",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 880,
    "precioVenta": 1100,
    "stock": 32,
    "stockMinimo": 8
  },
  {
    "id": "queso-cremoso-la-paulina-300g",
    "nombre": "Queso Cremoso La Paulina 300g",
    "ean": "7790000001482",
    "codigoInterno": "LAC-006",
    "categoria": "Lácteos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 3360,
    "precioVenta": 4200,
    "stock": 43,
    "stockMinimo": 8
  },
  {
    "id": "queso-rallado-la-serenisima-120g",
    "nombre": "Queso Rallado La Serenísima 120g",
    "ean": "7790000001499",
    "codigoInterno": "LAC-007",
    "categoria": "Lácteos",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 1520,
    "precioVenta": 1900,
    "stock": 42,
    "stockMinimo": 8
  },
  {
    "id": "manteca-la-serenisima-200g",
    "nombre": "Manteca La Serenísima 200g",
    "ean": "7790000001505",
    "codigoInterno": "LAC-008",
    "categoria": "Lácteos",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 2080,
    "precioVenta": 2600,
    "stock": 35,
    "stockMinimo": 8
  },
  {
    "id": "crema-de-leche-la-serenisima-200g",
    "nombre": "Crema de Leche La Serenísima 200g",
    "ean": "7790000001512",
    "codigoInterno": "LAC-009",
    "categoria": "Lácteos",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 1680,
    "precioVenta": 2100,
    "stock": 34,
    "stockMinimo": 8
  },
  {
    "id": "huevos-blancos-docena",
    "nombre": "Huevos Blancos Docena",
    "ean": "7790000001529",
    "codigoInterno": "LAC-010",
    "categoria": "Lácteos",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2560,
    "precioVenta": 3200,
    "stock": 44,
    "stockMinimo": 8
  },
  {
    "id": "dulce-de-leche-repostero-1kg",
    "nombre": "Dulce de Leche Repostero 1kg",
    "ean": "7790000001536",
    "codigoInterno": "LAC-011",
    "categoria": "Lácteos",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 5440,
    "precioVenta": 6800,
    "stock": 47,
    "stockMinimo": 8
  },
  {
    "id": "flan-la-serenisima-vainilla-120g",
    "nombre": "Flan La Serenísima Vainilla 120g",
    "ean": "7790000001543",
    "codigoInterno": "LAC-012",
    "categoria": "Lácteos",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 1040,
    "precioVenta": 1300,
    "stock": 30,
    "stockMinimo": 8
  },
  {
    "id": "lavandina-ayudin-1l",
    "nombre": "Lavandina Ayudín 1L",
    "ean": "7790000001550",
    "codigoInterno": "LIM-001",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1444,
    "precioVenta": 1950,
    "stock": 42,
    "stockMinimo": 8
  },
  {
    "id": "lavandina-ayudin-2l",
    "nombre": "Lavandina Ayudín 2L",
    "ean": "7790000001567",
    "codigoInterno": "LIM-002",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2370,
    "precioVenta": 3200,
    "stock": 40,
    "stockMinimo": 8
  },
  {
    "id": "detergente-magistral-limon-750ml",
    "nombre": "Detergente Magistral Limón 750ml",
    "ean": "7790000001574",
    "codigoInterno": "LIM-003",
    "categoria": "Limpieza",
    "proveedor": "Procter & Gamble",
    "unidadVenta": "unidad",
    "precioCosto": 2074,
    "precioVenta": 2800,
    "stock": 6,
    "stockMinimo": 8
  },
  {
    "id": "detergente-ala-750ml",
    "nombre": "Detergente Ala 750ml",
    "ean": "7790000001581",
    "codigoInterno": "LIM-004",
    "categoria": "Limpieza",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 1778,
    "precioVenta": 2400,
    "stock": 26,
    "stockMinimo": 8
  },
  {
    "id": "jabon-en-polvo-skip-800g",
    "nombre": "Jabón en Polvo Skip 800g",
    "ean": "7790000001598",
    "codigoInterno": "LIM-005",
    "categoria": "Limpieza",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 3111,
    "precioVenta": 4200,
    "stock": 31,
    "stockMinimo": 8
  },
  {
    "id": "jabon-en-polvo-ariel-800g",
    "nombre": "Jabón en Polvo Ariel 800g",
    "ean": "7790000001604",
    "codigoInterno": "LIM-006",
    "categoria": "Limpieza",
    "proveedor": "Procter & Gamble",
    "unidadVenta": "unidad",
    "precioCosto": 3407,
    "precioVenta": 4600,
    "stock": 46,
    "stockMinimo": 8
  },
  {
    "id": "jabon-en-polvo-ala-800g",
    "nombre": "Jabón en Polvo Ala 800g",
    "ean": "7790000001611",
    "codigoInterno": "LIM-007",
    "categoria": "Limpieza",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 2519,
    "precioVenta": 3400,
    "stock": 28,
    "stockMinimo": 8
  },
  {
    "id": "jabon-blanco-federal-200g",
    "nombre": "Jabón Blanco Federal 200g",
    "ean": "7790000001628",
    "codigoInterno": "LIM-008",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 593,
    "precioVenta": 800,
    "stock": 37,
    "stockMinimo": 8
  },
  {
    "id": "suavizante-vivere-900ml",
    "nombre": "Suavizante Vivere 900ml",
    "ean": "7790000001635",
    "codigoInterno": "LIM-009",
    "categoria": "Limpieza",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 2296,
    "precioVenta": 3100,
    "stock": 31,
    "stockMinimo": 8
  },
  {
    "id": "papel-higienico-higienol-4u",
    "nombre": "Papel Higiénico Higienol 4u",
    "ean": "7790000001642",
    "codigoInterno": "LIM-010",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2667,
    "precioVenta": 3600,
    "stock": 32,
    "stockMinimo": 8
  },
  {
    "id": "papel-higienico-elite-4u",
    "nombre": "Papel Higiénico Elite 4u",
    "ean": "7790000001659",
    "codigoInterno": "LIM-011",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2889,
    "precioVenta": 3900,
    "stock": 40,
    "stockMinimo": 8
  },
  {
    "id": "rollo-de-cocina-sussex-3u",
    "nombre": "Rollo de Cocina Sussex 3u",
    "ean": "7790000001666",
    "codigoInterno": "LIM-012",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2519,
    "precioVenta": 3400,
    "stock": 43,
    "stockMinimo": 8
  },
  {
    "id": "servilletas-elite-100u",
    "nombre": "Servilletas Elite 100u",
    "ean": "7790000001673",
    "codigoInterno": "LIM-013",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1185,
    "precioVenta": 1600,
    "stock": 34,
    "stockMinimo": 8
  },
  {
    "id": "desodorante-de-ambiente-poett-360ml",
    "nombre": "Desodorante de Ambiente Poett 360ml",
    "ean": "7790000001680",
    "codigoInterno": "LIM-014",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2148,
    "precioVenta": 2900,
    "stock": 47,
    "stockMinimo": 8
  },
  {
    "id": "limpiador-cif-crema-750ml",
    "nombre": "Limpiador Cif Crema 750ml",
    "ean": "7790000001697",
    "codigoInterno": "LIM-015",
    "categoria": "Limpieza",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 2370,
    "precioVenta": 3200,
    "stock": 41,
    "stockMinimo": 8
  },
  {
    "id": "limpiador-mr-musculo-bano-500ml",
    "nombre": "Limpiador Mr Músculo Baño 500ml",
    "ean": "7790000001703",
    "codigoInterno": "LIM-016",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2222,
    "precioVenta": 3000,
    "stock": 33,
    "stockMinimo": 8
  },
  {
    "id": "insecticida-raid-mata-moscas-360ml",
    "nombre": "Insecticida Raid Mata Moscas 360ml",
    "ean": "7790000001710",
    "codigoInterno": "LIM-017",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 3111,
    "precioVenta": 4200,
    "stock": 35,
    "stockMinimo": 8
  },
  {
    "id": "lustramuebles-blem-360ml",
    "nombre": "Lustramuebles Blem 360ml",
    "ean": "7790000001727",
    "codigoInterno": "LIM-018",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2444,
    "precioVenta": 3300,
    "stock": 26,
    "stockMinimo": 8
  },
  {
    "id": "esponja-doble-uso-mortimer",
    "nombre": "Esponja Doble Uso Mortimer",
    "ean": "7790000001734",
    "codigoInterno": "LIM-019",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 519,
    "precioVenta": 700,
    "stock": 31,
    "stockMinimo": 8
  },
  {
    "id": "bolsas-de-residuo-45x60-10u",
    "nombre": "Bolsas de Residuo 45x60 10u",
    "ean": "7790000001741",
    "codigoInterno": "LIM-020",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1407,
    "precioVenta": 1900,
    "stock": 41,
    "stockMinimo": 8
  },
  {
    "id": "trapo-de-piso-rejilla",
    "nombre": "Trapo de Piso Rejilla",
    "ean": "7790000001758",
    "codigoInterno": "LIM-021",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 889,
    "precioVenta": 1200,
    "stock": 43,
    "stockMinimo": 8
  },
  {
    "id": "virulana-metalica-3u",
    "nombre": "Virulana Metálica 3u",
    "ean": "7790000001765",
    "codigoInterno": "LIM-022",
    "categoria": "Limpieza",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 667,
    "precioVenta": 900,
    "stock": 37,
    "stockMinimo": 8
  },
  {
    "id": "shampoo-sedal-340ml",
    "nombre": "Shampoo Sedal 340ml",
    "ean": "7790000001772",
    "codigoInterno": "PER-001",
    "categoria": "Perfumería",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 3862,
    "precioVenta": 5600,
    "stock": 4,
    "stockMinimo": 6
  },
  {
    "id": "shampoo-plusbelle-900ml",
    "nombre": "Shampoo Plusbelle 900ml",
    "ean": "7790000001789",
    "codigoInterno": "PER-002",
    "categoria": "Perfumería",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2621,
    "precioVenta": 3800,
    "stock": 42,
    "stockMinimo": 6
  },
  {
    "id": "shampoo-head-shoulders-375ml",
    "nombre": "Shampoo Head & Shoulders 375ml",
    "ean": "7790000001796",
    "codigoInterno": "PER-003",
    "categoria": "Perfumería",
    "proveedor": "Procter & Gamble",
    "unidadVenta": "unidad",
    "precioCosto": 4690,
    "precioVenta": 6800,
    "stock": 35,
    "stockMinimo": 6
  },
  {
    "id": "acondicionador-sedal-340ml",
    "nombre": "Acondicionador Sedal 340ml",
    "ean": "7790000001802",
    "codigoInterno": "PER-004",
    "categoria": "Perfumería",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 3862,
    "precioVenta": 5600,
    "stock": 24,
    "stockMinimo": 6
  },
  {
    "id": "jabon-de-tocador-dove-90g",
    "nombre": "Jabón de Tocador Dove 90g",
    "ean": "7790000001819",
    "codigoInterno": "PER-005",
    "categoria": "Perfumería",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 1103,
    "precioVenta": 1600,
    "stock": 36,
    "stockMinimo": 6
  },
  {
    "id": "jabon-de-tocador-lux-125g",
    "nombre": "Jabón de Tocador Lux 125g",
    "ean": "7790000001826",
    "codigoInterno": "PER-006",
    "categoria": "Perfumería",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 828,
    "precioVenta": 1200,
    "stock": 34,
    "stockMinimo": 6
  },
  {
    "id": "desodorante-rexona-aerosol-150ml",
    "nombre": "Desodorante Rexona Aerosol 150ml",
    "ean": "7790000001833",
    "codigoInterno": "PER-007",
    "categoria": "Perfumería",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 2897,
    "precioVenta": 4200,
    "stock": 38,
    "stockMinimo": 6
  },
  {
    "id": "desodorante-axe-aerosol-150ml",
    "nombre": "Desodorante Axe Aerosol 150ml",
    "ean": "7790000001840",
    "codigoInterno": "PER-008",
    "categoria": "Perfumería",
    "proveedor": "Unilever",
    "unidadVenta": "unidad",
    "precioCosto": 3172,
    "precioVenta": 4600,
    "stock": 21,
    "stockMinimo": 6
  },
  {
    "id": "pasta-dental-colgate-triple-accion-90g",
    "nombre": "Pasta Dental Colgate Triple Acción 90g",
    "ean": "7790000001857",
    "codigoInterno": "PER-009",
    "categoria": "Perfumería",
    "proveedor": "Colgate-Palmolive",
    "unidadVenta": "unidad",
    "precioCosto": 1655,
    "precioVenta": 2400,
    "stock": 35,
    "stockMinimo": 6
  },
  {
    "id": "cepillo-dental-colgate",
    "nombre": "Cepillo Dental Colgate",
    "ean": "7790000001864",
    "codigoInterno": "PER-010",
    "categoria": "Perfumería",
    "proveedor": "Colgate-Palmolive",
    "unidadVenta": "unidad",
    "precioCosto": 1241,
    "precioVenta": 1800,
    "stock": 38,
    "stockMinimo": 6
  },
  {
    "id": "algodon-estrella-100g",
    "nombre": "Algodón Estrella 100g",
    "ean": "7790000001871",
    "codigoInterno": "PER-011",
    "categoria": "Perfumería",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1310,
    "precioVenta": 1900,
    "stock": 28,
    "stockMinimo": 6
  },
  {
    "id": "cotonetes-100u",
    "nombre": "Cotonetes 100u",
    "ean": "7790000001888",
    "codigoInterno": "PER-012",
    "categoria": "Perfumería",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 966,
    "precioVenta": 1400,
    "stock": 23,
    "stockMinimo": 6
  },
  {
    "id": "toallitas-femeninas-always-8u",
    "nombre": "Toallitas Femeninas Always 8u",
    "ean": "7790000001895",
    "codigoInterno": "PER-013",
    "categoria": "Perfumería",
    "proveedor": "Procter & Gamble",
    "unidadVenta": "unidad",
    "precioCosto": 1793,
    "precioVenta": 2600,
    "stock": 24,
    "stockMinimo": 6
  },
  {
    "id": "panales-pampers-confort-sec-m-30u",
    "nombre": "Pañales Pampers Confort Sec M 30u",
    "ean": "7790000001901",
    "codigoInterno": "PER-014",
    "categoria": "Perfumería",
    "proveedor": "Procter & Gamble",
    "unidadVenta": "unidad",
    "precioCosto": 8828,
    "precioVenta": 12800,
    "stock": 3,
    "stockMinimo": 6
  },
  {
    "id": "panales-babysec-ultra-g-30u",
    "nombre": "Pañales Babysec Ultra G 30u",
    "ean": "7790000001918",
    "codigoInterno": "PER-015",
    "categoria": "Perfumería",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 7724,
    "precioVenta": 11200,
    "stock": 30,
    "stockMinimo": 6
  },
  {
    "id": "preservativos-prime-3u",
    "nombre": "Preservativos Prime 3u",
    "ean": "7790000001925",
    "codigoInterno": "PER-016",
    "categoria": "Perfumería",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2000,
    "precioVenta": 2900,
    "stock": 21,
    "stockMinimo": 6
  },
  {
    "id": "alcohol-en-gel-250ml",
    "nombre": "Alcohol en Gel 250ml",
    "ean": "7790000001932",
    "codigoInterno": "PER-017",
    "categoria": "Perfumería",
    "proveedor": "Mayorista Sur",
    "unidadVenta": "unidad",
    "precioCosto": 1655,
    "precioVenta": 2400,
    "stock": 41,
    "stockMinimo": 6
  },
  {
    "id": "alcohol-70-250ml",
    "nombre": "Alcohol 70% 250ml",
    "ean": "7790000001949",
    "codigoInterno": "PER-018",
    "categoria": "Perfumería",
    "proveedor": "Mayorista Sur",
    "unidadVenta": "unidad",
    "precioCosto": 1310,
    "precioVenta": 1900,
    "stock": 38,
    "stockMinimo": 6
  },
  {
    "id": "pilas-duracell-aa-x2",
    "nombre": "Pilas Duracell AA x2",
    "ean": "7790000001956",
    "codigoInterno": "KIO-001",
    "categoria": "Kiosco",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2286,
    "precioVenta": 3200,
    "stock": 46,
    "stockMinimo": 8
  },
  {
    "id": "pilas-duracell-aaa-x2",
    "nombre": "Pilas Duracell AAA x2",
    "ean": "7790000001963",
    "codigoInterno": "KIO-002",
    "categoria": "Kiosco",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2286,
    "precioVenta": 3200,
    "stock": 48,
    "stockMinimo": 8
  },
  {
    "id": "encendedor-bic",
    "nombre": "Encendedor Bic",
    "ean": "7790000001970",
    "codigoInterno": "KIO-003",
    "categoria": "Kiosco",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1071,
    "precioVenta": 1500,
    "stock": 31,
    "stockMinimo": 8
  },
  {
    "id": "fosforos-tres-patitos-3u",
    "nombre": "Fósforos Tres Patitos 3u",
    "ean": "7790000001987",
    "codigoInterno": "KIO-004",
    "categoria": "Kiosco",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 500,
    "precioVenta": 700,
    "stock": 43,
    "stockMinimo": 8
  },
  {
    "id": "panuelos-descartables-kleenex-10u",
    "nombre": "Pañuelos Descartables Kleenex 10u",
    "ean": "7790000001994",
    "codigoInterno": "KIO-005",
    "categoria": "Kiosco",
    "proveedor": "Kimberly-Clark",
    "unidadVenta": "unidad",
    "precioCosto": 929,
    "precioVenta": 1300,
    "stock": 41,
    "stockMinimo": 8
  },
  {
    "id": "velas-larga-duracion-6u",
    "nombre": "Velas Larga Duración 6u",
    "ean": "7790000002007",
    "codigoInterno": "KIO-006",
    "categoria": "Kiosco",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1000,
    "precioVenta": 1400,
    "stock": 29,
    "stockMinimo": 8
  }
]
