// ⚠️ GENERADO por scripts/cargar-catalogo.mjs — NO editar a mano.
// Rubro: panaderia · Fuente: scripts/catalogos-seed/panaderia.csv · 43 productos
// Regenerar: node scripts/cargar-catalogo.mjs panaderia
import type { ProductoCatalogo } from "./tipos"

export const categorias: string[] = [
  "Facturas",
  "Panadería",
  "Pastelería",
  "Sándwiches",
  "Almacén",
  "Bebidas",
  "Fiambrería"
]

export const proveedores: string[] = [
  "Elaboración propia",
  "Molinos Río de la Plata",
  "La Serenísima",
  "Distribuidora Norte",
  "Establecimiento Las Marías",
  "Coca-Cola FEMSA"
]

export const catalogo: ProductoCatalogo[] = [
  {
    "id": "medialuna-de-manteca",
    "nombre": "Medialuna de Manteca",
    "ean": "7790000000010",
    "codigoInterno": "FAC-001",
    "categoria": "Facturas",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 219,
    "precioVenta": 350,
    "stock": 51,
    "stockMinimo": 10
  },
  {
    "id": "medialunas-docena",
    "nombre": "Medialunas Docena",
    "ean": "7790000000027",
    "codigoInterno": "FAC-002",
    "categoria": "Facturas",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 2375,
    "precioVenta": 3800,
    "stock": 42,
    "stockMinimo": 10
  },
  {
    "id": "factura-surtida-docena",
    "nombre": "Factura Surtida Docena",
    "ean": "7790000000034",
    "codigoInterno": "FAC-003",
    "categoria": "Facturas",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 2250,
    "precioVenta": 3600,
    "stock": 49,
    "stockMinimo": 10
  },
  {
    "id": "vigilante",
    "nombre": "Vigilante",
    "ean": "7790000000041",
    "codigoInterno": "FAC-004",
    "categoria": "Facturas",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 219,
    "precioVenta": 350,
    "stock": 46,
    "stockMinimo": 10
  },
  {
    "id": "canoncito-de-dulce-de-leche",
    "nombre": "Cañoncito de Dulce de Leche",
    "ean": "7790000000058",
    "codigoInterno": "FAC-005",
    "categoria": "Facturas",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 313,
    "precioVenta": 500,
    "stock": 41,
    "stockMinimo": 10
  },
  {
    "id": "bola-de-fraile",
    "nombre": "Bola de Fraile",
    "ean": "7790000000065",
    "codigoInterno": "FAC-006",
    "categoria": "Facturas",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 281,
    "precioVenta": 450,
    "stock": 33,
    "stockMinimo": 10
  },
  {
    "id": "churro-relleno",
    "nombre": "Churro Relleno",
    "ean": "7790000000072",
    "codigoInterno": "FAC-007",
    "categoria": "Facturas",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 375,
    "precioVenta": 600,
    "stock": 41,
    "stockMinimo": 10
  },
  {
    "id": "pan-frances-por-kg",
    "nombre": "Pan Francés por kg",
    "ean": "7790000000089",
    "codigoInterno": "PAN-001",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 1419,
    "precioVenta": 2200,
    "stock": 34,
    "stockMinimo": 10
  },
  {
    "id": "pan-flauta",
    "nombre": "Pan Flauta",
    "ean": "7790000000096",
    "codigoInterno": "PAN-002",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 581,
    "precioVenta": 900,
    "stock": 41,
    "stockMinimo": 10
  },
  {
    "id": "pan-de-salvado-por-kg",
    "nombre": "Pan de Salvado por kg",
    "ean": "7790000000102",
    "codigoInterno": "PAN-003",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 1677,
    "precioVenta": 2600,
    "stock": 48,
    "stockMinimo": 10
  },
  {
    "id": "figaza",
    "nombre": "Figaza",
    "ean": "7790000000119",
    "codigoInterno": "PAN-004",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 452,
    "precioVenta": 700,
    "stock": 53,
    "stockMinimo": 10
  },
  {
    "id": "pan-lactal-casero",
    "nombre": "Pan Lactal Casero",
    "ean": "7790000000126",
    "codigoInterno": "PAN-005",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 2065,
    "precioVenta": 3200,
    "stock": 49,
    "stockMinimo": 10
  },
  {
    "id": "pan-de-hamburguesa-4u",
    "nombre": "Pan de Hamburguesa 4u",
    "ean": "7790000000133",
    "codigoInterno": "PAN-006",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 1032,
    "precioVenta": 1600,
    "stock": 41,
    "stockMinimo": 10
  },
  {
    "id": "pan-de-pancho-4u",
    "nombre": "Pan de Pancho 4u",
    "ean": "7790000000140",
    "codigoInterno": "PAN-007",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 968,
    "precioVenta": 1500,
    "stock": 33,
    "stockMinimo": 10
  },
  {
    "id": "grisines-de-semola-200g",
    "nombre": "Grisines de Sémola 200g",
    "ean": "7790000000157",
    "codigoInterno": "PAN-008",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 903,
    "precioVenta": 1400,
    "stock": 34,
    "stockMinimo": 10
  },
  {
    "id": "criollitos-por-kg",
    "nombre": "Criollitos por kg",
    "ean": "7790000000164",
    "codigoInterno": "PAN-009",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 1935,
    "precioVenta": 3000,
    "stock": 52,
    "stockMinimo": 10
  },
  {
    "id": "mignon-por-kg",
    "nombre": "Mignon por kg",
    "ean": "7790000000171",
    "codigoInterno": "PAN-010",
    "categoria": "Panadería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 1484,
    "precioVenta": 2300,
    "stock": 36,
    "stockMinimo": 10
  },
  {
    "id": "budin-de-vainilla",
    "nombre": "Budín de Vainilla",
    "ean": "7790000000188",
    "codigoInterno": "PAS-001",
    "categoria": "Pastelería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 2000,
    "precioVenta": 3200,
    "stock": 37,
    "stockMinimo": 10
  },
  {
    "id": "budin-marmolado",
    "nombre": "Budín Marmolado",
    "ean": "7790000000195",
    "codigoInterno": "PAS-002",
    "categoria": "Pastelería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 2000,
    "precioVenta": 3200,
    "stock": 46,
    "stockMinimo": 10
  },
  {
    "id": "porcion-de-torta-rogel",
    "nombre": "Porción de Torta Rogel",
    "ean": "7790000000201",
    "codigoInterno": "PAS-003",
    "categoria": "Pastelería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 1625,
    "precioVenta": 2600,
    "stock": 43,
    "stockMinimo": 10
  },
  {
    "id": "porcion-de-tarta-de-ricota",
    "nombre": "Porción de Tarta de Ricota",
    "ean": "7790000000218",
    "codigoInterno": "PAS-004",
    "categoria": "Pastelería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 1500,
    "precioVenta": 2400,
    "stock": 36,
    "stockMinimo": 10
  },
  {
    "id": "alfajor-de-maicena",
    "nombre": "Alfajor de Maicena",
    "ean": "7790000000225",
    "codigoInterno": "PAS-005",
    "categoria": "Pastelería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 438,
    "precioVenta": 700,
    "stock": 31,
    "stockMinimo": 10
  },
  {
    "id": "pepas-por-kg",
    "nombre": "Pepas por kg",
    "ean": "7790000000232",
    "codigoInterno": "PAS-006",
    "categoria": "Pastelería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 2625,
    "precioVenta": 4200,
    "stock": 44,
    "stockMinimo": 10
  },
  {
    "id": "palmerita",
    "nombre": "Palmerita",
    "ean": "7790000000249",
    "codigoInterno": "PAS-007",
    "categoria": "Pastelería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 250,
    "precioVenta": 400,
    "stock": 31,
    "stockMinimo": 10
  },
  {
    "id": "masa-fina-por-kg",
    "nombre": "Masa Fina por kg",
    "ean": "7790000000256",
    "codigoInterno": "PAS-008",
    "categoria": "Pastelería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 6125,
    "precioVenta": 9800,
    "stock": 49,
    "stockMinimo": 10
  },
  {
    "id": "cookie-con-chips",
    "nombre": "Cookie con Chips",
    "ean": "7790000000263",
    "codigoInterno": "PAS-009",
    "categoria": "Pastelería",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 563,
    "precioVenta": 900,
    "stock": 45,
    "stockMinimo": 10
  },
  {
    "id": "sandwich-de-miga-simple",
    "nombre": "Sándwich de Miga Simple",
    "ean": "7790000000270",
    "codigoInterno": "SAN-001",
    "categoria": "Sándwiches",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 467,
    "precioVenta": 700,
    "stock": 41,
    "stockMinimo": 6
  },
  {
    "id": "sandwich-de-miga-triple",
    "nombre": "Sándwich de Miga Triple",
    "ean": "7790000000287",
    "codigoInterno": "SAN-002",
    "categoria": "Sándwiches",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 867,
    "precioVenta": 1300,
    "stock": 41,
    "stockMinimo": 6
  },
  {
    "id": "prepizza",
    "nombre": "Prepizza",
    "ean": "7790000000294",
    "codigoInterno": "SAN-003",
    "categoria": "Sándwiches",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 1067,
    "precioVenta": 1600,
    "stock": 27,
    "stockMinimo": 6
  },
  {
    "id": "tapa-de-empanada-docena",
    "nombre": "Tapa de Empanada Docena",
    "ean": "7790000000300",
    "codigoInterno": "SAN-004",
    "categoria": "Sándwiches",
    "proveedor": "Molinos Río de la Plata",
    "unidadVenta": "unidad",
    "precioCosto": 1267,
    "precioVenta": 1900,
    "stock": 27,
    "stockMinimo": 6
  },
  {
    "id": "tapa-de-tarta",
    "nombre": "Tapa de Tarta",
    "ean": "7790000000317",
    "codigoInterno": "SAN-005",
    "categoria": "Sándwiches",
    "proveedor": "Molinos Río de la Plata",
    "unidadVenta": "unidad",
    "precioCosto": 933,
    "precioVenta": 1400,
    "stock": 28,
    "stockMinimo": 6
  },
  {
    "id": "empanada-de-carne",
    "nombre": "Empanada de Carne",
    "ean": "7790000000324",
    "codigoInterno": "SAN-006",
    "categoria": "Sándwiches",
    "proveedor": "Elaboración propia",
    "unidadVenta": "unidad",
    "precioCosto": 800,
    "precioVenta": 1200,
    "stock": 34,
    "stockMinimo": 6
  },
  {
    "id": "leche-la-serenisima-sachet-1l",
    "nombre": "Leche La Serenísima Sachet 1L",
    "ean": "7790000000331",
    "codigoInterno": "ALM-001",
    "categoria": "Almacén",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 1172,
    "precioVenta": 1500,
    "stock": 39,
    "stockMinimo": 12
  },
  {
    "id": "huevos-docena",
    "nombre": "Huevos Docena",
    "ean": "7790000000348",
    "codigoInterno": "ALM-002",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 2500,
    "precioVenta": 3200,
    "stock": 42,
    "stockMinimo": 12
  },
  {
    "id": "azucar-ledesma-1kg",
    "nombre": "Azúcar Ledesma 1kg",
    "ean": "7790000000355",
    "codigoInterno": "ALM-003",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 1484,
    "precioVenta": 1900,
    "stock": 47,
    "stockMinimo": 12
  },
  {
    "id": "yerba-taragui-1kg",
    "nombre": "Yerba Taragüí 1kg",
    "ean": "7790000000362",
    "codigoInterno": "ALM-004",
    "categoria": "Almacén",
    "proveedor": "Establecimiento Las Marías",
    "unidadVenta": "unidad",
    "precioCosto": 3828,
    "precioVenta": 4900,
    "stock": 55,
    "stockMinimo": 12
  },
  {
    "id": "cafe-la-virginia-250g",
    "nombre": "Café La Virginia 250g",
    "ean": "7790000000379",
    "codigoInterno": "ALM-005",
    "categoria": "Almacén",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 3750,
    "precioVenta": 4800,
    "stock": 56,
    "stockMinimo": 12
  },
  {
    "id": "manteca-la-serenisima-200g",
    "nombre": "Manteca La Serenísima 200g",
    "ean": "7790000000386",
    "codigoInterno": "ALM-006",
    "categoria": "Almacén",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 2031,
    "precioVenta": 2600,
    "stock": 47,
    "stockMinimo": 12
  },
  {
    "id": "dulce-de-leche-la-serenisima-400g",
    "nombre": "Dulce de Leche La Serenísima 400g",
    "ean": "7790000000393",
    "codigoInterno": "ALM-007",
    "categoria": "Almacén",
    "proveedor": "La Serenísima",
    "unidadVenta": "unidad",
    "precioCosto": 2500,
    "precioVenta": 3200,
    "stock": 40,
    "stockMinimo": 12
  },
  {
    "id": "coca-cola-1-5l",
    "nombre": "Coca-Cola 1.5L",
    "ean": "7790000000409",
    "codigoInterno": "BEB-001",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 2370,
    "precioVenta": 3200,
    "stock": 47,
    "stockMinimo": 12
  },
  {
    "id": "agua-villa-del-sur-2l",
    "nombre": "Agua Villa del Sur 2L",
    "ean": "7790000000416",
    "codigoInterno": "BEB-002",
    "categoria": "Bebidas",
    "proveedor": "Coca-Cola FEMSA",
    "unidadVenta": "unidad",
    "precioCosto": 1333,
    "precioVenta": 1800,
    "stock": 40,
    "stockMinimo": 12
  },
  {
    "id": "jamon-cocido-por-kg",
    "nombre": "Jamón Cocido por kg",
    "ean": "7790000000423",
    "codigoInterno": "FIA-001",
    "categoria": "Fiambrería",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 9846,
    "precioVenta": 12800,
    "stock": 17,
    "stockMinimo": 4
  },
  {
    "id": "queso-de-maquina-por-kg",
    "nombre": "Queso de Máquina por kg",
    "ean": "7790000000430",
    "codigoInterno": "FIA-002",
    "categoria": "Fiambrería",
    "proveedor": "Distribuidora Norte",
    "unidadVenta": "unidad",
    "precioCosto": 9077,
    "precioVenta": 11800,
    "stock": 24,
    "stockMinimo": 4
  }
]
