// ⚠️ GENERADO por scripts/cargar-catalogo.mjs — NO editar a mano.
// Rubro: verduleria · Fuente: scripts/catalogos-seed/verduleria.csv · 35 productos
// Regenerar: node scripts/cargar-catalogo.mjs verduleria
import type { ProductoCatalogo } from "./tipos"

export const categorias: string[] = [
  "Verduras",
  "Frutas"
]

export const proveedores: string[] = [
  "Mercado de Abasto",
  "Quinta local"
]

export const catalogo: ProductoCatalogo[] = [
  {
    "id": "tomate-redondo",
    "nombre": "Tomate redondo",
    "ean": "7790000000010",
    "codigoInterno": "VER-001",
    "categoria": "Verduras",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 889,
    "precioVenta": 1200,
    "stock": 32,
    "stockMinimo": 8
  },
  {
    "id": "papa-blanca",
    "nombre": "Papa blanca",
    "ean": "7790000000027",
    "codigoInterno": "VER-002",
    "categoria": "Verduras",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 593,
    "precioVenta": 800,
    "stock": 26,
    "stockMinimo": 8
  },
  {
    "id": "cebolla",
    "nombre": "Cebolla",
    "ean": "7790000000034",
    "codigoInterno": "VER-003",
    "categoria": "Verduras",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 667,
    "precioVenta": 900,
    "stock": 36,
    "stockMinimo": 8
  },
  {
    "id": "zanahoria",
    "nombre": "Zanahoria",
    "ean": "7790000000041",
    "codigoInterno": "VER-004",
    "categoria": "Verduras",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 741,
    "precioVenta": 1000,
    "stock": 40,
    "stockMinimo": 8
  },
  {
    "id": "zapallo-anco",
    "nombre": "Zapallo anco",
    "ean": "7790000000058",
    "codigoInterno": "VER-005",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 704,
    "precioVenta": 950,
    "stock": 26,
    "stockMinimo": 8
  },
  {
    "id": "batata",
    "nombre": "Batata",
    "ean": "7790000000065",
    "codigoInterno": "VER-006",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 815,
    "precioVenta": 1100,
    "stock": 39,
    "stockMinimo": 8
  },
  {
    "id": "lechuga-criolla",
    "nombre": "Lechuga criolla",
    "ean": "7790000000072",
    "codigoInterno": "VER-007",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 1333,
    "precioVenta": 1800,
    "stock": 3,
    "stockMinimo": 8
  },
  {
    "id": "acelga",
    "nombre": "Acelga",
    "ean": "7790000000089",
    "codigoInterno": "VER-008",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 1037,
    "precioVenta": 1400,
    "stock": 34,
    "stockMinimo": 8
  },
  {
    "id": "espinaca",
    "nombre": "Espinaca",
    "ean": "7790000000096",
    "codigoInterno": "VER-009",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 1630,
    "precioVenta": 2200,
    "stock": 38,
    "stockMinimo": 8
  },
  {
    "id": "morron-rojo",
    "nombre": "Morrón rojo",
    "ean": "7790000000102",
    "codigoInterno": "VER-010",
    "categoria": "Verduras",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 2370,
    "precioVenta": 3200,
    "stock": 24,
    "stockMinimo": 8
  },
  {
    "id": "morron-verde",
    "nombre": "Morrón verde",
    "ean": "7790000000119",
    "codigoInterno": "VER-011",
    "categoria": "Verduras",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 1778,
    "precioVenta": 2400,
    "stock": 36,
    "stockMinimo": 8
  },
  {
    "id": "choclo",
    "nombre": "Choclo",
    "ean": "7790000000126",
    "codigoInterno": "VER-012",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 963,
    "precioVenta": 1300,
    "stock": 38,
    "stockMinimo": 8
  },
  {
    "id": "zapallito",
    "nombre": "Zapallito",
    "ean": "7790000000133",
    "codigoInterno": "VER-013",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 1111,
    "precioVenta": 1500,
    "stock": 29,
    "stockMinimo": 8
  },
  {
    "id": "berenjena",
    "nombre": "Berenjena",
    "ean": "7790000000140",
    "codigoInterno": "VER-014",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 1259,
    "precioVenta": 1700,
    "stock": 27,
    "stockMinimo": 8
  },
  {
    "id": "pepino",
    "nombre": "Pepino",
    "ean": "7790000000157",
    "codigoInterno": "VER-015",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 1185,
    "precioVenta": 1600,
    "stock": 30,
    "stockMinimo": 8
  },
  {
    "id": "ajo",
    "nombre": "Ajo",
    "ean": "7790000000164",
    "codigoInterno": "VER-016",
    "categoria": "Verduras",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 3556,
    "precioVenta": 4800,
    "stock": 33,
    "stockMinimo": 8
  },
  {
    "id": "remolacha",
    "nombre": "Remolacha",
    "ean": "7790000000171",
    "codigoInterno": "VER-017",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 815,
    "precioVenta": 1100,
    "stock": 35,
    "stockMinimo": 8
  },
  {
    "id": "chaucha",
    "nombre": "Chaucha",
    "ean": "7790000000188",
    "codigoInterno": "VER-018",
    "categoria": "Verduras",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 1926,
    "precioVenta": 2600,
    "stock": 39,
    "stockMinimo": 8
  },
  {
    "id": "manzana-roja",
    "nombre": "Manzana roja",
    "ean": "7790000000195",
    "codigoInterno": "FRU-001",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 1333,
    "precioVenta": 1800,
    "stock": 24,
    "stockMinimo": 8
  },
  {
    "id": "manzana-verde",
    "nombre": "Manzana verde",
    "ean": "7790000000201",
    "codigoInterno": "FRU-002",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 1407,
    "precioVenta": 1900,
    "stock": 38,
    "stockMinimo": 8
  },
  {
    "id": "banana",
    "nombre": "Banana",
    "ean": "7790000000218",
    "codigoInterno": "FRU-003",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 1111,
    "precioVenta": 1500,
    "stock": 48,
    "stockMinimo": 8
  },
  {
    "id": "naranja",
    "nombre": "Naranja",
    "ean": "7790000000225",
    "codigoInterno": "FRU-004",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 815,
    "precioVenta": 1100,
    "stock": 27,
    "stockMinimo": 8
  },
  {
    "id": "mandarina",
    "nombre": "Mandarina",
    "ean": "7790000000232",
    "codigoInterno": "FRU-005",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 963,
    "precioVenta": 1300,
    "stock": 27,
    "stockMinimo": 8
  },
  {
    "id": "limon",
    "nombre": "Limón",
    "ean": "7790000000249",
    "codigoInterno": "FRU-006",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 1185,
    "precioVenta": 1600,
    "stock": 43,
    "stockMinimo": 8
  },
  {
    "id": "pera",
    "nombre": "Pera",
    "ean": "7790000000256",
    "codigoInterno": "FRU-007",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 1407,
    "precioVenta": 1900,
    "stock": 44,
    "stockMinimo": 8
  },
  {
    "id": "uva",
    "nombre": "Uva",
    "ean": "7790000000263",
    "codigoInterno": "FRU-008",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 2519,
    "precioVenta": 3400,
    "stock": 37,
    "stockMinimo": 8
  },
  {
    "id": "frutilla",
    "nombre": "Frutilla",
    "ean": "7790000000270",
    "codigoInterno": "FRU-009",
    "categoria": "Frutas",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 3333,
    "precioVenta": 4500,
    "stock": 2,
    "stockMinimo": 5
  },
  {
    "id": "durazno",
    "nombre": "Durazno",
    "ean": "7790000000287",
    "codigoInterno": "FRU-010",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 1926,
    "precioVenta": 2600,
    "stock": 28,
    "stockMinimo": 8
  },
  {
    "id": "ciruela",
    "nombre": "Ciruela",
    "ean": "7790000000294",
    "codigoInterno": "FRU-011",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 1778,
    "precioVenta": 2400,
    "stock": 32,
    "stockMinimo": 8
  },
  {
    "id": "kiwi",
    "nombre": "Kiwi",
    "ean": "7790000000300",
    "codigoInterno": "FRU-012",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 2815,
    "precioVenta": 3800,
    "stock": 32,
    "stockMinimo": 8
  },
  {
    "id": "anana",
    "nombre": "Ananá",
    "ean": "7790000000317",
    "codigoInterno": "FRU-013",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 1630,
    "precioVenta": 2200,
    "stock": 44,
    "stockMinimo": 8
  },
  {
    "id": "melon",
    "nombre": "Melón",
    "ean": "7790000000324",
    "codigoInterno": "FRU-014",
    "categoria": "Frutas",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 1037,
    "precioVenta": 1400,
    "stock": 34,
    "stockMinimo": 8
  },
  {
    "id": "sandia",
    "nombre": "Sandía",
    "ean": "7790000000331",
    "codigoInterno": "FRU-015",
    "categoria": "Frutas",
    "proveedor": "Quinta local",
    "unidadVenta": "kg",
    "precioCosto": 667,
    "precioVenta": 900,
    "stock": 45,
    "stockMinimo": 8
  },
  {
    "id": "pomelo",
    "nombre": "Pomelo",
    "ean": "7790000000348",
    "codigoInterno": "FRU-016",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 889,
    "precioVenta": 1200,
    "stock": 39,
    "stockMinimo": 8
  },
  {
    "id": "palta",
    "nombre": "Palta",
    "ean": "7790000000355",
    "codigoInterno": "FRU-017",
    "categoria": "Frutas",
    "proveedor": "Mercado de Abasto",
    "unidadVenta": "kg",
    "precioCosto": 3852,
    "precioVenta": 5200,
    "stock": 48,
    "stockMinimo": 8
  }
]
